---
# Installs logstash

- name: Starting logstash role
  debug:
    msg: "{{ lookup('pipe','date') }}"

# Look for the shared_folder variable for Vagrant-based installs
- name: Look for Vagrant shared folder
  stat: path=/home/vagrant/shared/installers/
  register: shared_folder

- name: Default to installing logstash
  set_fact:
    logstash_install_flag: true

- name: Get current logstash version
  shell: /opt/logstash/bin/logstash --version | python -c 'import sys; print(sys.stdin.read().split()[-1])'
  register: logstash_version_cmd
  ignore_errors: yes
  changed_when: false

- name: Set logstash_install_flag to false if es version is already installed
  set_fact:
    logstash_install_flag: false
  when: logstash_version_cmd.rc == 0 and (logstash_pkg_version == logstash_version_cmd.stdout)

- name: Look for existing logstash Ubuntu repository
  stat: path="/etc/apt/sources.list.d/packages_elastic_co_logstash_2_2_debian.list"
  register: logstash_repo_file
  when: logstash_install_flag == true

- name: Add logstash repository, as needed
  apt_repository:
    repo: "deb http://packages.elastic.co/logstash/2.2/debian stable main"
  when: logstash_install_flag == true and logstash_repo_file.stat.exists == false

- name: Update apt-cache if older than two hours
  apt:
    update_cache: yes
    cache_valid_time: 7200
  when: logstash_install_flag == true

# For Vagrant-managed environments
- include: install-from-shared-dir.yml
  when: shared_folder.stat.exists and logstash_install_flag == true and "vagrant_managed" in group_names

- name: Install logstash
  apt:
    pkg: "{{ item }}"
    state: installed
    force: yes
  with_items:
    - logstash

- name: Finished with logstash role
  debug:
    msg: "{{ lookup('pipe','date') }}"